name: Publish Site

on:
  push:
    tags:
      - "*"

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: Set up local secrets
        env:
          MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: echo -e "MAPBOX_KEY=$MAPBOX_KEY\nBASE_URL=$BASE_URL" > local.env
          
      - name: Build dist
        run: yarn run build
        
      - name: Deploy 🚉
        if: success()
        uses: JamesIves/github-pages-deploy-action@3.5.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          SINGLE_COMMIT: true 
